config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods
  resources :foods, except: [:update]
  resources :recipes, except: [:update]
  resources :shopping_list, only: [:index]
  devise_for :users
  root to: "home#index"

  get 'public_recipes', to: 'public_recipes#index'
  get '/general_shopping_list', to: 'shopping_list#index', as: 'shopping_list'
  post '/general_shopping_list', to: 'shopping_list#generate', as: 'generate_shopping_list'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :recipe
  belongs_to :user

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipes, through: :recipe_foods
  has_many :recipe_foods

  validates :name, presence: true
  validates :measurement_units, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods
  has_many :cart_items

  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :description, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
  attribute :quantity, :integer

  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :foods
  has_many :recipes
  has_many :cart_items

  attr_accessor :confirmation_token

  validates :email, presence: true, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = current_user.foods.build(food_params)

    if @food.save
      redirect_to food_url(@food), notice: 'Food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = current_user.foods.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_units, :price, :quantity, :public)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @foods = Food.all
    @recipes = Recipe.includes(:user, :foods).where(public: true)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.includes(:user, :foods).where(public: true)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[show edit update destroy]

  # GET /recipe_foods or /recipe_foods.json
  def index
    @recipe_foods = RecipeFood.all
  end

  # GET /recipe_foods/1 or /recipe_foods/1.json
  def show; end

  # GET /recipe_foods/new
  def new
    @recipe_food = RecipeFood.new
  end

  # GET /recipe_foods/1/edit
  def edit; end

  # POST /recipe_foods or /recipe_foods.json
  def create
    @recipe_food = RecipeFood.new(recipe_food_params)

    respond_to do |format|
      if @recipe_food.save
        format.html { redirect_to recipe_food_url(@recipe_food), notice: 'Recipe food was successfully created.' }
        format.json { render :show, status: :created, location: @recipe_food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_foods/1 or /recipe_foods/1.json
  def update
    respond_to do |format|
      if @recipe_food.update(recipe_food_params)
        format.html { redirect_to recipe_food_url(@recipe_food), notice: 'Recipe food was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_foods/1 or /recipe_foods/1.json
  def destroy
    @recipe_food.destroy

    respond_to do |format|
      format.html { redirect_to recipe_foods_url, notice: 'Recipe food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.fetch(:recipe_food).permit(:food_quantity, :food_id, :recipe_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def show
    @foods = @recipe.foods.includes(:recipe_foods)
    @recipe_food = RecipeFood.find_by(recipe: @recipe, food: @foods)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  private

  def set_recipe
    @recipe = current_user.recipes.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = CartItem.where(user: current_user)
  end

  def generate
    @recipe = Recipe.find(params[:recipe_id])
    @recipe.recipe_foods.each do |recipe_food|
      food = recipe_food.food
      CartItem.create(
        name: food.name,
        measurement_unit: food.measurement_units,
        price: food.price,
        quantity: recipe_food.food_quantity,
        recipe: @recipe,
        user: current_user
      )
    end

    redirect_to shopping_list_path, notice: 'Shopping list generated successfully.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |attribute, message| %>
          <li><%= "#{attribute.to_s.humanize} #{message}" %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field lol">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :measurement_units %>
    <%= form.select :measurement_units, ['grams', 'Kilograms', 'Units', 'Litles'] %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text">$</span>
      </div>
      <%= form.text_field :price, class: 'form-control' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :public %>
    <%= form.check_box :public %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to "Add Food", new_food_path, class: "add-food-link" %>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Measurement Unit</th>
        <th>Unit Price</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @foods.each do |food| %>
        <%= render food %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.measurement_units %></td>
          <td>$<%= food.price %></td>
          <td><%= button_to "Delete", food, method: :delete, class: "delete-link" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<!-- app/views/foods/show.html.erb -->

<p class="notice"><%= notice %></p>
<div class="foodss">

<div class="food-details">
  <p><strong>Name:</strong> <%= @food.name %></p>
  <p><strong>Measurement Units:</strong> <%= @food.measurement_units %></p>
  <p><strong>Price:</strong> <%= @food.price %></p>
  <p><strong>Quantity:</strong> <%= @food.quantity %></p>
  <p><strong>Public:</strong> <%= @food.public %></p>
</div>

<div class="actions">
  <%= link_to "Back", foods_path, class: "back-link" %>
  <%= button_to "Delete", @food, method: :delete, class: "delete-button" %>
</div>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to Recipe</title>
</head>
<body>
  <div class="publicRecipes" >
    <h1>
        Public Recipes
    </h1>
    <% if @recipes.present? %>
        <% @recipes.each do |recipe| %>

            <div class="recipeContainer" onclick=<%="visitRecipe(#{recipe.id})"%> >  
                <div class="recipeLeft">
                    <h2>
                        <%= recipe.name %>
                    </h2>
                    <h4>
                        By: <%= recipe.user.email %>
                    </h4>
                </div>
                <div class="recipeRight">
                    <h4>
                        Total food items: <%= recipe.foods.length %>
                    </h4>
                    <% if recipe.foods.length > 0 %>
                        <h4>
                            Total price: <%= recipe.foods.sum { |food| food.price * food.quantity } %>
                        </h4>
                    <% else %>
                        <h4>
                            Total price: 0
                        </h4>
                    <% end %>
                </div>
            </div>
        <% end %>
    <% else %>
        No Public recipes
    <% end %>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/public_recipes/index.html.erb
<div class="publicRecipes" >
    <h1>
        Public Recipes
    </h1>
    <% if @recipes.present? %>
        <% @recipes.each do |recipe| %>

            <div class="recipeContainer" onclick=<%="visitRecipe(#{recipe.id})"%> >  
                <div class="recipeLeft">
                    <h2>
                        <%= recipe.name %>
                    </h2>
                    <h4>
                        By: <%= recipe.user.name %>
                    </h4>
                </div>
                <div class="recipeRight">
                    <h4>
                        Total food items: <%= recipe.foods.length %>
                    </h4>
                    <% if recipe.foods.length > 0 %>
                        <h4>
                            Total price: <%= recipe.foods.sum { |food| food.price * food.quantity } %>
                        </h4>
                    <% else %>
                        <h4>
                            Total price: 0
                        </h4>
                    <% end %>
                </div>
            </div>
        <% end %>
    <% else %>
        No Public recipes
    <% end %>
</div>

app/views/recipe_foods/_form.html.erb
<%= form_with(model: recipe_food) do |form| %>
  <% if recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

      <ul>
        <% recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="lol">
  <%= form.label :food_id %>
  <%= form.collection_select :food_id, Food.all, :id, :name %>
</div>

<div>
  <%= form.label :food_quantity %>
  <%= form.number_field :food_quantity %>
</div>

<div>
  <%= form.label :recipe_id %>
  <%= form.collection_select :recipe_id, Recipe.all, :id, :name %>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipe_foods/_recipe_food.html.erb
<div id="<%= dom_id recipe_food %>">
</div>

app/views/recipe_foods/edit.html.erb
<h1>Editing recipe food</h1>

<%= render "form", recipe_food: @recipe_food %>

<br>

<div>
  <%= link_to "Show this recipe food", @recipe_food %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>
</div>

app/views/recipe_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<h1>New recipe food</h1>

<%= render "form", recipe_food: @recipe_food %>

<br>

<div>
  <%= link_to "Back to recipe foods", recipe_foods_path %>
</div>

app/views/recipe_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe_food %>

<div>
  <%= link_to "Edit this recipe food", edit_recipe_food_path(@recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>

  <%= button_to "Destroy this recipe food", @recipe_food, method: :delete %>
</div>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
    <% if recipe.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(recipe.errors.count, 'error') %> prohibited this recipe from being saved:</h2>
  
        <ul>
          <% recipe.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field lol">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :preparation_time %>
      <%= form.number_field :preparation_time %>
    </div>
  
    <div class="field">
      <%= form.label :cooking_time %>
      <%= form.number_field :cooking_time %>
    </div>
  
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>
  
    <div class="field">
      <%= form.label :public %>
      <%= form.check_box :public %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<div class="header">
    <div class="act">
      <%= link_to 'Add Recipe', new_recipe_path %>
      <%= link_to "New recipe_food", new_recipe_food_path %>
    </div>
 

  <% @recipes.each do |recipe| %>
    <div class="recipe">
      <div class="action">
      <h3><td><%= link_to "#{recipe.name}", recipe, method: :delete, class: "remove-btn" %></h3>
        <%= button_to 'REMOVE', recipe, method: :delete, class: 'remove-btn' %>
      </div>
      <div class="description">
        <p><%= recipe.description %></p>
      </div>
    </div>
  <% end %>
  </div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<div class= "recipe-2">
<div>
<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>
<div class="recip">
<p>
  <strong>Preparation Time:</strong>
  <%= @recipe.preparation_time %>
</p>

<p>
<% if !current_user.nil? && current_user.id == @recipe.user_id %>
<%= form_for @recipe do |f| %>
  <div class="custom-control custom-switch">
    <%= f.check_box :public, id: "visibility-toggle", class: "custom-control-input" %>
    <%= f.label :public, class: "custom-control-label", for: "visibility-toggle" %>
  </div>
  
  <%= f.submit "Update Visibility", class: "btn btn-primary" %>
  <%end%>
<% end %>
</p>
</div>

<p>
  <strong>Cooking Time:</strong>
  <%= @recipe.cooking_time %>
</p>
<div class="gret">
<div class="treess">
<%= link_to 'Back', recipes_path %>
</div>

<% if user_signed_in? %>
<%= button_to 'Generate Shopping List', generate_shopping_list_path(recipe_id: @recipe.id), method: :post, class: 'recipesButton' %>
<% end %>
</div>
</div>
<div>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <% food_quantity = food.recipe_foods.find { |rf| rf.recipe_id == @recipe.id }&.food_quantity || 0 %>
          <td><%= food_quantity %></td>
          <td>$<%= food.price * food_quantity %></td>
          <td><div>
          <% if @recipe_food %>
          <%= link_to "Modify", edit_recipe_food_path(@recipe_food) %> |
          <%= button_to "Remove", @recipe_food, method: :delete %>
        <% end %>
        </div></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  </div>

app/views/shared/_navbar.html.erb
<!-- app/views/shared/_navbar.html.erb -->

<nav class="navbar">
<ul class="nav-items">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Food List', foods_path %></li>
    <li><%= link_to 'Recipes List', recipes_path %></li>
    <li><%= link_to 'Shopping List', shopping_list_index_path %></li>
  </ul>
  <ul class="nav-items">
  <% if user_signed_in? %>
  <li>
    <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'btn' %>
  </li>
<% else %>
  <li>
    <%= link_to 'Login', new_user_session_path, class: 'btn' %>
  </li>
  <li>
    <%= link_to 'Sign-up', new_user_registration_path, class: 'btn' %>
  </li>
<% end %>
</ul>
</nav>

app/views/shopping_list/index.html.erb
<div class="shoppingContainer" >
    <h1 class="sho">Shopping List</h1>
    <% if  @foods.length > 0 %>
    <div class="shops">
            <h3>Amount of food items to buy: <%= @foods.count %></h3>
            <h1>Total value of food needed: <%= (@foods.inject(0) { |sum , food| sum += food.price * food.quantity }).round(2) %> </h1>
            </div>
            <table>
            <tr>
              <th>Food</th>
              <th>Quantity</th>
              <th>Price</th>
              <th>Recipe</th> <!-- New column for recipe -->
            </tr>
            <% @foods.each do |food| %>
              <tr>
                <td><%= food.name %></td>
                <td><%= food.quantity %></td>
                <td><%= (food.price * food.quantity).round(2) %></td>
                <td><%= food.recipe.name %></td> <!-- Display recipe name -->
              </tr>
            <% end %>
          </table>
    <% else %>
        <h1>No Items in the cart</h1>
    <% end %>
</div>